name = "TransportPolynomials"
uuid = "69b6ae23-bf73-4db6-99ee-ef78af08ccd7"
authors = ["Peter Amorese <peter.amorese@gmail.com>"]
version = "0.1.0"

[deps]
BellBruno = "2cc14a73-b19f-41ce-8eb5-0eba8210e186"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
